namespace: tectonic
name: core
version: 1.0.0
readme: README.md
authors:
- gsi@fing.edu.uy
description: Core functions
license:
- GPL-3.0-only
tags:
  - "tectonic"
  - "core"
dependencies: {}
repository: https://github.com/GSI-Fing-Udelar/tectonic
homepage: http://example.com
issues: https://www.fing.edu.uy/inco/proyectos/tectonic
build_ignore: []