---
- name: Get Moodle information
  hosts: moodle
  become: true
  gather_facts: false

  tasks:
    - name: Read credentials file
      ansible.builtin.slurp:
        src: /root/credentials
      register: moodle_credentials
      failed_when: false

    - name: Set credentials fact
      ansible.builtin.set_fact:
        moodle_credentials_content: "{{ moodle_credentials['content'] | b64decode }}"
      when: moodle_credentials is defined and not moodle_credentials.failed

