---
- name: Upgrade pip to latest version
  ansible.builtin.command: >
    {{ python_executable }} -m pip install --upgrade pip
  register: pip_upgrade
  changed_when: pip_upgrade.rc == 0

- name: Install Python libraries
  ansible.builtin.pip:
    name: "{{ python_libraries }}"
    state: present
    executable: "{{ pip_executable }}"
  when: python_libraries | length > 0