- name: "Test (for ubuntu 22.04)"
  hosts: guacamole
  become: true
  gather_facts: true

  vars:
    guacamole_version: 1.6.0

  tasks:
    - name: "Update repos"
      ansible.builtin.apt:
        update_cache: yes

    - name: Install packages
      ansible.builtin.package:
        name: 
          - libcairo2-dev
          - libjpeg-turbo8-dev
          - libpng-dev
          - libtool-bin
          - uuid-dev
          - libossp-uuid-dev
          - libavcodec-dev
          - libavformat-dev
          - libavutil-dev
          - libswscale-dev
          - freerdp2-dev
          - libpango1.0-dev
          - libssh2-1-dev
          - libtelnet-dev
          - libvncserver-dev
          - libwebsockets-dev
          - libpulse-dev
          - libssl-dev
          - libvorbis-dev
          - libwebp-dev
          - make
          - tomcat9
          - tomcat9-admin
          - tomcat9-common
          - tomcat9-user
        state: present

    - name: Download guacamole
      ansible.builtin.unarchive:
        src: "https://downloads.apache.org/guacamole/{{ guacamole_version }}/source/guacamole-server-{{ guacamole_version }}.tar.gz"
        dest: /root/
        remote_src: yes

    - name: Build guacamole
      block:
        - name: Build guacamole | Configure
          ansible.builtin.command: ./configure --with-systemd-dir=/etc/systemd/system/
          args:
            chdir: /root/guacamole-server-{{ guacamole_version }}
        - name: Build guacamole | Make
          ansible.builtin.command: make
          args:
            chdir: /root/guacamole-server-{{ guacamole_version }}
        - name: Build guacamole | Make install
          ansible.builtin.command: make install
          args:
            chdir: /root/guacamole-server-{{ guacamole_version }}
        - name: Build guacamole | ldconfig
          ansible.builtin.command: ldconfig
          args:
            chdir: /root/guacamole-server-{{ guacamole_version }}

    - name: Create Guacamole user
      block:
        - name: Create Guacamole user | Create user
          ansible.builtin.user:
            name: guacd
            shell: /sbin/nologin
            home: /var/lib/guacd

        - name: Create Guacamole user | Create user home
          ansible.builtin.file:
            path: /var/lib/guacd
            state: directory
            mode: '0755'
            owner: guacd
            group: guacd 

        - name: Create Guacamole user | Adjust service file
          ansible.builtin.lineinfile:
            path: /etc/systemd/system/guacd.service
            regexp: '^User='
            line: User=guacd

    - name: Download guacamole webapp
      ansible.builtin.get_url:
        url: "https://downloads.apache.org/guacamole/{{ guacamole_version }}/binary/guacamole-{{ guacamole_version }}.war"
        dest: /var/lib/tomcat9/webapps/guacamole.war

    - name: Configure guacamole
      block:
        - name: Configure guacamole | Create configuration directory
          ansible.builtin.file:
            path: /etc/guacamole
            state: directory
            mode: '0755'

        - name: Configure guacamole | Create guacamole properties file
          ansible.builtin.copy:
            dest: /etc/guacamole/guacamole.properties
            content: |
                guacd-hostname: localhost
                guacd-port: 4822
                auth-provider: net.sourceforge.guacamole.net.basic.BasicFileAuthenticationProvider
                basic-user-mapping: /etc/guacamole/user-mapping.xml

        - name: Configure guacamole | Create guacd config file
          ansible.builtin.copy:
            dest: /etc/guacamole/guacd.conf
            content: |
              [server]
              bind_host = 127.0.0.1
              bind_port = 4822

    - name: Configure guacamole brute force protection
      block:
        - name: Configure guacamole brute force protection | Create extensions directory
          ansible.builtin.file:
            path: /etc/guacamole/extensions
            state: directory
            mode: '0755'

        - name: Configure guacamole brute force protection | Download extension
          ansible.builtin.unarchive:
            src: "https://apache.org/dyn/closer.lua/guacamole/{{ guacamole_version }}/binary/guacamole-auth-ban-{{ guacamole_version }}.tar.gz?action=download"
            dest: /root
            remote_src: yes

        - name: Configure guacamole brute force protection | Copy extension
          ansible.builtin.copy:
            src: "/root/guacamole-auth-ban-{{ guacamole_version }}/guacamole-auth-ban-{{ guacamole_version }}.jar"
            dest: /etc/guacamole/extensions/
            remote_src: yes

    - name: Enable and start services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: restarted
        enabled: true
        daemon_reload : true
      with_items:
        - tomcat9
        - guacd
